config/routes.rb
Rails.application.routes.draw do
  resources :games
  devise_for :users
  root to: "home#index"
  get '/history', to: 'games#index'
  get '/log',     to: 'games#new'
end

app/models/concerns/rankeable.rb
module Rankeable
  extend ActiveSupport::Concern

  def update_rating! game
    ratings = new_ratings(self.rating, game.opponent.rating, game.won ? 1:0)

    self.update_column :rating, ratings['player1']
    game.opponent.update_column :rating, ratings['player2']
  end

  def new_ratings(player1_rating,player2_rating,result,k_value=32,should_round=true)
    #Assign actual individual results
    player1_result = result
    player2_result = 1 - result

    #Calculate expected results
    player1_expectation = 1/(1+10**((player2_rating - player1_rating)/400.0)) #the .0 is important to force float operations!))
    player2_expectation = 1/(1+10**((player1_rating - player2_rating)/400.0))

    #Calculate new ratings
    player1_new_rating = player1_rating + (k_value*(player1_result - player1_expectation))
    player2_new_rating = player2_rating + (k_value*(player2_result - player2_expectation))

    #Optional rounding
    if should_round
      # int rounds down and forces type
      player1_new_rating = player1_new_rating.round
      player2_new_rating = player2_new_rating.round
    end

    # Create a dictionary to return and do so!
    new_ratings_hash = Hash.new
    new_ratings_hash['player1'] = player1_new_rating
    new_ratings_hash['player2'] = player2_new_rating

    new_ratings_hash
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
  belongs_to :opponent, class_name: 'User'

  before_save :calculate_result
  after_create :update_ratings

  scope :of_user, ->(user) {
    games = Game.arel_table
    where(games[:user_id].eq(user).or(games[:opponent_id].eq(user)))
  }

  validates_presence_of :user_id, :opponent_id
  validate :has_winner

  def calculate_result
    if user_score > opponent_score
      self.won = true
    end
  end

  def has_winner
    if user_score == 21
      return true if opponent_score < user_score
    elsif opponent_score == 21
      return true if user_score < opponent_score
    end

    errors.add(:base, "There must be a winner player with score 21")
    return false
  end

  def update_ratings
    user.update_rating! self
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  include Rankeable

  devise :database_authenticatable, :registerable, :trackable, :validatable

  scope :opponents, ->(user) { where.not(id: user) }

  def to_s
    email.split("@").first.titleize
  end

  def games
    Game.of_user(id)
  end

  def opponents
    User.opponents(id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  def index
    @games = current_user.games
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # POST /games
  def create
    @game = Game.new(game_params)
    @game.user = current_user

    if @game.save
      redirect_to history_path, notice: 'Game was successfully created.'
    else
      render :new
    end
  end

  private
    # Only allow a trusted parameter "white list" through.
    def game_params
      params.require(:game).permit(:date_played, :user_id, :opponent_id, :user_score, :opponent_score)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.order(rating: :desc)
  end

  def history; end

  def log; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
  def opponent(game)
    if current_user == game.user
      game.opponent
    else
      game.user
    end
  end

  def result(game)
    if current_user == game.user
      if game.won
        "W"
      else
        "L"
      end
    else
      if game.won
        "L"
      else
        "W"
      end
    end
  end

  def score(game)
    if current_user == game.user
      "#{game.user_score}-#{game.opponent_score}"
    else
      "#{game.opponent_score}-#{game.user_score}"
    end
  end
end

app/views/games/_form.html.erb
<%= form_for(@game, html: {class: "form-horizontal center"}) do |f| %>
  <% if @game.errors.any? %>
    <div class="alert alert-warning">
      <h4><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :date_played, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :date_played, {}, {class: "date form-control"} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :opponent_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select :opponent_id, current_user.opponents, :id, :to_s, {}, {class: "form-control"} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :user_score, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :user_score, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :opponent_score, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :opponent_score, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-default" %>
      <%= link_to 'cancel', games_path %>
    </div>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<% unless notice.blank? %>
  <div class="alert alert-success" role="alert"><%= notice %></div>
<% end %>

<h1 class="page-header">History</h1>

<table class="table">
  <thead>
    <tr>
      <th>Date played</th>
      <th>Opponent</th>
      <th>Score</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.date_played %></td>
        <td><%= opponent(game) %></td>
        <td><%= score(game) %></td>
        <td><%= result(game) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/new.html.erb
<h1 class='page-header'>Log Game</h1>

<%= render 'form' %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date played:</strong>
  <%= @game.date_played %>
</p>

<p>
  <strong>User:</strong>
  <%= @game.user_id %>
</p>

<p>
  <strong>Opponent:</strong>
  <%= @game.opponent_id %>
</p>

<p>
  <strong>User score:</strong>
  <%= @game.user_score %>
</p>

<p>
  <strong>Opponent score:</strong>
  <%= @game.opponent_score %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/home/history.html.erb
<h1 class='page-header'>History</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%= image_tag('history.png') %>

app/views/home/index.html.erb
<h1 class='page-header'>Leaderboard</h1>

<table class="table">
  <thead>
    <tr>
      <th>Rank</th>
      <th>Name</th>
      <th>Score</th>
      <th>Games Played</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each_with_index do |user, index| %>
      <tr>
        <td><%= index+1 %></td>
        <td><%= user %></td>
        <td><%= user.rating %></td>
        <td><%= user.games.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/log.html.erb
<h1 class='page-header'>Log Game</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%= render 'games/form' %>

<%= image_tag('log_game.png') %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pingpong</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= link_to 'Log Game', '/log', class: 'btn btn-success navbar-btn' %>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Leadboard', root_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><a href="/history">History</a></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pingpong Leaderboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="/assets/jquery.js" type="text/javascript"></script>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", integrity: "sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js", integrity: "sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>